package com.nanolaba.nrg.core;

import com.nanolaba.nrg.NRG;
import com.nanolaba.nrg.core.freeze.FreezeBlockProcessor;
import com.nanolaba.nrg.widgets.NRGWidget;
import org.apache.commons.io.FileUtils;

import java.io.BufferedReader;
import java.io.File;
import java.io.IOException;
import java.io.StringReader;
import java.nio.charset.Charset;
import java.util.Collection;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.function.Function;

/**
 * Orchestrates the generation pipeline for a single source template.
 *
 * <p>Holds a {@link GeneratorConfig} (parsed from the source body) and lazily produces one
 * {@link GenerationResult} per language declared via {@code nrg.languages}. Results are
 * computed on first access via {@link #getResult(String)} / {@link #getResults()} and cached
 * for the lifetime of the instance.
 *
 * <p>Each result is a head comment plus the rendered body — {@link IfBlockProcessor} prunes
 * inactive branches first, then every remaining line is wrapped in a {@link TemplateLine} for
 * visibility check, property/widget substitution, and final output assembly.
 */
public class Generator {

    private final GeneratorConfig config;
    private Map<String, GenerationResult> results;

    public Generator(File sourceFile, Charset charset) throws IOException {
        this(sourceFile, charset, null);
    }

    public Generator(File sourceFile, Charset charset, List<NRGWidget> widgets) throws IOException {
        this(sourceFile, FileUtils.readFileToString(sourceFile, charset), widgets);
    }

    public Generator(File sourceFile, String sourceBody) {
        this(sourceFile, sourceBody, null);
    }

    public Generator(File sourceFile, String sourceBody, List<NRGWidget> widgets) {
        config = new GeneratorConfig(sourceFile, sourceBody, widgets);
    }

    public Generator(File sourceFile, String sourceBody, List<NRGWidget> widgets,
                     Function<String, String> envProvider) {
        config = new GeneratorConfig(sourceFile, sourceBody, widgets, envProvider);
    }

    public Generator(File sourceFile, String sourceBody, List<NRGWidget> widgets,
                     Function<String, String> envProvider, PomReader pomReader) {
        config = new GeneratorConfig(sourceFile, sourceBody, widgets, envProvider, pomReader);
    }

    public Generator(File sourceFile, String sourceBody, List<NRGWidget> widgets,
                     Function<String, String> envProvider, PomReader pomReader,
                     NpmReader npmReader, GradleReader gradleReader) {
        config = new GeneratorConfig(sourceFile, sourceBody, widgets,
                envProvider, pomReader, npmReader, gradleReader);
    }

    protected void generateContents() {
        for (String language : config.getLanguages()) {
            results.put(language, generateContent(language));
        }
    }

    protected void generateContentIfNecessary() {
        if (results == null) {
            results = new HashMap<>();
            generateContents();
        }
    }

    private GenerationResult generateContent(String language) {
        GenerationResult result = new GenerationResult(language);
        result.getContent().append(generateHeadComment(language));

        String body = IfBlockProcessor.process(config.getSourceFileBody(), config, language);
        AtomicInteger counter = new AtomicInteger(0);
        new BufferedReader(new StringReader(body))
                .lines()
                .map(s -> new TemplateLine(config, s, counter.getAndIncrement()))
                .filter(t -> t.isLineVisible(language))
                .map(t -> t.generateLine(language))
                .forEachOrdered(line -> result.getContent().append(line).append(System.lineSeparator()));

        if (config.isRootGenerator()) {
            String resolved = FreezeBlockProcessor.resolve(result.getContent().toString(), config, language);
            resolved = resolved
                    .replace("\\$", "$")
                    .replace("<\\!--", "<!--")
                    .replace("<!--\\@", "<!--@");
            result.getContent().setLength(0);
            result.getContent().append(resolved);
        }

        return result;
    }

    protected String generateHeadComment(String language) {
        if (Boolean.parseBoolean(config.getProperties().getProperty(NRGConstants.PROPERTY_NO_HEADER))) {
            return "";
        }
        String custom = config.getProperties().getProperty(NRGConstants.PROPERTY_HEADER_TEXT);
        if (custom != null) {
            return interpretHeaderEscapes(custom) + System.lineSeparator();
        }
        return "<!-- This file was automatically generated by Nanolaba Readme Generator (NRG) " + NRG.getVersion() + " -->" + System.lineSeparator() +
                "<!-- Visit https://github.com/nanolaba/readme-generator for details -->" + System.lineSeparator();
    }

    /**
     * Translates the four escape sequences {@code \n}, {@code \r}, {@code \t}, and {@code \\}
     * inside a custom header string into their respective characters. {@code \n} maps to
     * {@link System#lineSeparator()} so the rendered header matches the platform convention
     * used everywhere else in the output.
     *
     * <p>Single-pass scan to keep escapes literal — replacing them with {@link String#replace}
     * one at a time would let an earlier substitution's output (e.g. a literal {@code \n}
     * unescaped from a {@code \\n} input) be re-interpreted by the next pass.
     */
    private static String interpretHeaderEscapes(String raw) {
        StringBuilder sb = new StringBuilder(raw.length());
        int i = 0;
        while (i < raw.length()) {
            char c = raw.charAt(i);
            if (c == '\\' && i + 1 < raw.length()) {
                char next = raw.charAt(i + 1);
                switch (next) {
                    case 'n': sb.append(System.lineSeparator()); i += 2; continue;
                    case 'r': sb.append('\r'); i += 2; continue;
                    case 't': sb.append('\t'); i += 2; continue;
                    case '\\': sb.append('\\'); i += 2; continue;
                    default: break;
                }
            }
            sb.append(c);
            i++;
        }
        return sb.toString();
    }

    public GenerationResult getResult(String language) {
        generateContentIfNecessary();
        return results.get(language);
    }

    public Collection<GenerationResult> getResults() {
        generateContentIfNecessary();
        return results.values();
    }

    public GeneratorConfig getConfig() {
        return config;
    }
}
