package com.nanolaba.nrg;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * End-to-end coverage for NRG's line-ending behaviour. Locks in the contract from #48:
 * preserve the existing on-disk file's CRLF/LF convention on regeneration so the first
 * regeneration commit doesn't churn over OS-specific line endings.
 */
public class NRGLineEndingTest extends DefaultNRGTest {

    @TempDir
    Path tempDir;

    private Path writeBytes(String name, String body) throws IOException {
        Path p = tempDir.resolve(name);
        Files.write(p, body.getBytes(StandardCharsets.UTF_8));
        return p;
    }

    private String readBytes(Path p) throws IOException {
        return new String(Files.readAllBytes(p), StandardCharsets.UTF_8);
    }

    @Test
    public void testAutoPreservesCrlf() throws IOException {
        Path src = writeBytes("R.src.md", "<!--@nrg.languages=en-->\nLine A\nLine B\n");
        // Pre-existing output with CRLF — simulating a Windows contributor having written it.
        writeBytes("R.md", "<!-- This file was automatically generated by Nanolaba Readme Generator (NRG) -->\r\n");

        int code = NRG.run("-f", src.toString());
        assertEquals(0, code);

        String written = readBytes(tempDir.resolve("R.md"));
        assertTrue(written.contains("\r\n"),
                "expected CRLF preserved on regeneration, got: " + escape(written));
        // No bare LFs (every newline must be CRLF).
        assertFalse(written.replace("\r\n", "").contains("\n"),
                "expected only CRLF newlines, got mixed: " + escape(written));
    }

    @Test
    public void testAutoPreservesLf() throws IOException {
        Path src = writeBytes("R.src.md", "<!--@nrg.languages=en-->\nLine A\nLine B\n");
        // Pre-existing output with LF.
        writeBytes("R.md", "<!-- This file was automatically generated by Nanolaba Readme Generator (NRG) -->\n");

        int code = NRG.run("-f", src.toString());
        assertEquals(0, code);

        String written = readBytes(tempDir.resolve("R.md"));
        assertFalse(written.contains("\r"),
                "expected LF preserved on regeneration, got CR: " + escape(written));
    }

    @Test
    public void testExplicitLfOverridesExistingCrlf() throws IOException {
        Path src = writeBytes("R.src.md", "<!--@nrg.languages=en-->\nLine A\n");
        writeBytes("R.md", "old content\r\n");

        int code = NRG.run("--line-ending", "lf", "-f", src.toString());
        assertEquals(0, code);

        String written = readBytes(tempDir.resolve("R.md"));
        assertFalse(written.contains("\r"),
                "expected --line-ending=lf to drop CR, got: " + escape(written));
    }

    @Test
    public void testExplicitCrlfOverridesExistingLf() throws IOException {
        Path src = writeBytes("R.src.md", "<!--@nrg.languages=en-->\nLine A\n");
        writeBytes("R.md", "old content\n");

        int code = NRG.run("--line-ending", "crlf", "-f", src.toString());
        assertEquals(0, code);

        String written = readBytes(tempDir.resolve("R.md"));
        assertTrue(written.contains("\r\n"),
                "expected --line-ending=crlf to insert CRLF, got: " + escape(written));
        assertFalse(written.replace("\r\n", "").contains("\n"),
                "expected only CRLF, got mixed: " + escape(written));
    }

    @Test
    public void testInvalidLineEndingFlag() throws IOException {
        Path src = writeBytes("R.src.md", "<!--@nrg.languages=en-->\nLine A\n");

        int code = NRG.run("--line-ending", "cr", "-f", src.toString());
        assertEquals(1, code);
        String err = getErrAndClear();
        assertTrue(err.contains("Invalid line-ending mode"),
                "expected diagnostic about invalid mode, got: " + err);
    }

    @Test
    public void testCheckIgnoresLineEndingDifferenceInAutoMode() throws IOException {
        // A repository checked out on a Windows contributor's machine has CRLF in README.md,
        // but CI runs on Linux where the generator emits LF. Under --check (auto), this
        // should NOT fail.
        Path src = writeBytes("R.src.md", "<!--@nrg.languages=en-->\nstable line\n");
        // First, generate with auto mode to seed the on-disk file.
        assertEquals(0, NRG.run("-f", src.toString()));
        // Re-write the on-disk file with the OPPOSITE convention to whatever auto produced.
        String onDisk = readBytes(tempDir.resolve("R.md"));
        String flipped = onDisk.contains("\r\n")
                ? onDisk.replace("\r\n", "\n")
                : onDisk.replace("\n", "\r\n");
        Files.write(tempDir.resolve("R.md"), flipped.getBytes(StandardCharsets.UTF_8));

        int code = NRG.run("--check", "-f", src.toString());
        assertEquals(0, code, "auto-mode --check should ignore LE-only differences; stderr: " + getErrAndClear());
    }

    private static String escape(String s) {
        return s.replace("\r", "\\r").replace("\n", "\\n");
    }
}
