package com.nanolaba.nrg.widgets;

import com.nanolaba.logging.LOG;
import com.nanolaba.nrg.core.Generator;
import com.nanolaba.nrg.core.NRGConstants;
import org.apache.commons.lang3.StringUtils;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.io.File;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Path;
import java.time.Clock;
import java.util.Arrays;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

class ImportWidgetTest {

    @Test
    public void testImportAndTOC() throws IOException {
        File sourceFile = new File(getClass().getClassLoader().getResource("ImportWidgetTest/testTOC/test.src.md").getFile());
        Generator generator = new Generator(sourceFile, StandardCharsets.UTF_8);

        String bodyEn = generator.getResult("en").getContent().toString();
        LOG.info(bodyEn);
        assertTrue(bodyEn.contains("## HEADER1"));
        assertTrue(bodyEn.contains("## IGNORED_HEADER1"));
        assertTrue(bodyEn.contains("## HEADER2"));
        assertTrue(bodyEn.contains("## IGNORED_HEADER2"));
        assertTrue(bodyEn.contains("## HEADER3"));
        assertTrue(bodyEn.contains("## HEADER4"));
        assertTrue(bodyEn.contains(". [HEADER1](#header1)"));
        assertTrue(bodyEn.contains(". [HEADER2](#header2)"));
        assertTrue(bodyEn.contains(". [HEADER3](#header3)"));
        assertTrue(bodyEn.contains(". [HEADER4](#header4)"));

        assertFalse(bodyEn.contains(". [IGNORED_HEADER1](#ignored"));
        assertFalse(bodyEn.contains(". [IGNORED_HEADER2](#ignored"));
    }

    @Test
    public void testIgnoreMarkersInsideImportedFile() throws IOException {
        File sourceFile = new File(getClass().getClassLoader().getResource("ImportWidgetTest/testIgnoreInsideImport/test.src.md").getFile());
        Generator generator = new Generator(sourceFile, StandardCharsets.UTF_8);

        String body = generator.getResult("en").getContent().toString();
        LOG.info(body);
        assertTrue(body.contains("imported-before"));
        assertTrue(body.contains("imported-after"));
        assertFalse(body.contains("imported-inline-note"));
        assertFalse(body.contains("author note line 1"));
        assertFalse(body.contains("author note line 2"));
        assertFalse(body.contains("nrg.ignore"));
    }

    @Test
    public void testImportForDifferentLanguages() throws IOException {
        File sourceFile = new File(getClass().getClassLoader().getResource("ImportWidgetTest/testImportForDifferentLanguages/test.src.md").getFile());
        Generator generator = new Generator(sourceFile, StandardCharsets.UTF_8);

        String bodyEn = generator.getResult("en").getContent().toString();
        LOG.info(bodyEn);
        assertTrue(bodyEn.contains("Test"));

        String bodyRu = generator.getResult("ru").getContent().toString();
        LOG.info(bodyRu);
        assertTrue(bodyRu.contains("Тест"));
    }

    @Test
    public void testImportWidget() throws IOException {
        File sourceFile = new File(getClass().getClassLoader().getResource("ImportWidgetTest/README.src.md").getFile());
        Generator generator = new Generator(sourceFile, StandardCharsets.UTF_8);

        String bodyEn = generator.getResult("en").getContent().toString();
        LOG.info(bodyEn);

        assertEquals(1, StringUtils.countMatches(bodyEn, "<!-- This file was automatically generated by Nanolaba Readme Generator"));

        assertTrue(bodyEn.contains("<!--testComment1-->"));
        assertTrue(bodyEn.contains("<!--@testEscapedParam1=1-->"));

        // test.txt
        assertTrue(bodyEn.contains("Hello world!"));

        // folder/test.txt
        assertTrue(bodyEn.contains("Text from file in a folder."));

        // folder/testWin1251.txt
        assertTrue(bodyEn.contains("Текст в кодировке win1251"));

        // folder/test.src.md
        assertFalse(bodyEn.contains("<!--@testParameter=foo-->"));
        assertFalse(bodyEn.contains("${testParameter}"));
        assertTrue(bodyEn.contains("foobar"));
        assertFalse(bodyEn.contains("test1: ${globalParameter}"));
        assertTrue(bodyEn.contains("test1: This parameter is visible in all imported files"));
        assertTrue(bodyEn.contains("<!--testComment2-->"));
        assertTrue(bodyEn.contains("<!--@testEscapedParam2=1-->"));

        // folder/test-no-generation.src.md
        assertFalse(bodyEn.contains("<!--@unprocessedParameter=bar-->"));
        assertTrue(bodyEn.contains("foo${unprocessedParameter}"));
        assertTrue(bodyEn.contains("<!--testComment3-->"));
    }

    private String render(String fixturePath) throws IOException {
        File sourceFile = new File(getClass().getClassLoader().getResource(fixturePath).getFile());
        Generator generator = new Generator(sourceFile, StandardCharsets.UTF_8);
        return generator.getResult("en").getContent().toString();
    }

    @Test
    public void wrapTrueWithRegionWrapsInJavaFence() throws IOException {
        String body = render("ImportWidgetTest/extension/README-wrap-true-region.src.md");
        assertTrue(body.contains("```java"), body);
        assertTrue(body.contains("public void greet() {"), body);
        assertTrue(body.contains("System.out.println(\"hello\");"), body);
        // Markers stripped
        assertFalse(body.contains("nrg:begin:greet"));
        assertFalse(body.contains("nrg:end:greet"));
        // Closing fence
        String sep = System.lineSeparator();
        assertTrue(body.contains("```" + sep) || body.endsWith("```"), body);
    }

    @Test
    public void wrapTrueWithLinesWrapsInJavaFence() throws IOException {
        String body = render("ImportWidgetTest/extension/README-wrap-true-lines.src.md");
        assertTrue(body.contains("```java"), body);
        assertTrue(body.contains("public class Sample {"), body);
    }

    @Test
    public void wrapTrueWithLangWrapsFullFile() throws IOException {
        String body = render("ImportWidgetTest/extension/README-wrap-true-lang.src.md");
        assertTrue(body.contains("```text"), body);
        assertTrue(body.contains("plain text line 1"), body);
        assertTrue(body.contains("plain text line 3"), body);
    }

    @Test
    public void wrapDefaultsToFalse() throws IOException {
        // No wrap attribute — defaults to false; region content is emitted without a fence.
        String body = render("ImportWidgetTest/extension/README-wrap-default-region.src.md");
        assertFalse(body.contains("```java"), body);
        assertTrue(body.contains("public void greet() {"), body);
    }

    @Test
    public void wrapFalseDisablesFenceEvenWithRegion() throws IOException {
        String body = render("ImportWidgetTest/extension/README-wrap-false-region.src.md");
        assertFalse(body.contains("```java"), body);
        assertTrue(body.contains("public void greet() {"), body);
    }

    @Test
    public void wrapTrueWithoutSelectionWrapsFullFile() throws IOException {
        String body = render("ImportWidgetTest/extension/README-wrap-true-fullfile.src.md");
        assertTrue(body.contains("```java"), body);
        assertTrue(body.contains("package example;"), body);
    }

    @Test
    public void dedentFalsePreservesIndentation() throws IOException {
        String body = render("ImportWidgetTest/extension/README-dedent-false.src.md");
        // Original indentation (4 spaces from class body) is preserved
        assertTrue(body.contains("    public void greet() {"), body);
    }

    @Test
    public void langOverrideUsesGivenLanguage() throws IOException {
        String body = render("ImportWidgetTest/extension/README-lang-override.src.md");
        assertTrue(body.contains("```go"), body);
        assertFalse(body.contains("```java"), body);
    }

    @Test
    public void conflictingLinesAndRegionThrows() {
        RuntimeException ex = assertThrows(RuntimeException.class,
                () -> render("ImportWidgetTest/extension/README-conflict-lines-region.src.md"));
        assertTrue(ex.getMessage().contains("'lines' and 'region' are mutually exclusive"),
                () -> "unexpected: " + ex.getMessage());
    }

    @Test
    public void regionNotFoundThrows() {
        RuntimeException ex = assertThrows(RuntimeException.class,
                () -> render("ImportWidgetTest/extension/README-region-not-found.src.md"));
        assertTrue(ex.getMessage().contains("region"),
                () -> "unexpected: " + ex.getMessage());
    }

    @Test
    public void consecutiveImportsPreserveBlankLineSeparator() throws IOException {
        // Regression: the widget's default path (run-generator=true, wrap=false) must
        // preserve the trailing newline of imported content. Otherwise two consecutive
        // ${widget:import} calls collapse into adjacent lines with no blank line
        // between them, which breaks GitHub's markdown rendering when one fragment
        // ends in an HTML block and the next begins with a heading.
        String body = render("ImportWidgetTest/extension/README-two-imports.src.md");
        String sep = System.lineSeparator();
        assertTrue(body.contains("FIRST" + sep + sep + "SECOND"), body);
    }

    @Test
    void remoteImportFetchesAndRenders(@TempDir Path tmp) throws IOException {
        File src = writeFixture(tmp, "<!--@nrg.allowRemoteImports=true-->\n${widget:import(url='https://example.com/x')}\n");
        Generator g = new Generator(src, StandardCharsets.UTF_8, withCustomImport("REMOTE_BODY".getBytes(StandardCharsets.UTF_8)));
        assertTrue(g.getResult("en").getContent().toString().contains("REMOTE_BODY"));
    }

    @Test
    void remoteImportWithoutAllowFlagThrows(@TempDir Path tmp) throws IOException {
        File src = writeFixture(tmp, "${widget:import(url='https://example.com/x')}\n");
        Generator g = new Generator(src, StandardCharsets.UTF_8, withCustomImport("X".getBytes(StandardCharsets.UTF_8)));
        RuntimeException ex = assertThrows(RuntimeException.class, () -> g.getResult("en"));
        assertTrue(ex.getMessage().contains("nrg.allowRemoteImports") || (ex.getCause() != null && ex.getCause().getMessage().contains("nrg.allowRemoteImports")),
                () -> "unexpected: " + ex.getMessage());
    }

    @Test
    void remoteImportWithSha256Verifies(@TempDir Path tmp) throws IOException {
        String body = "REMOTE";
        String sha = Sha256Hex.hexOf(body.getBytes(StandardCharsets.UTF_8));
        File src = writeFixture(tmp,
                "<!--@nrg.allowRemoteImports=true-->\n${widget:import(url='https://example.com/x', sha256='" + sha + "')}\n");
        Generator g = new Generator(src, StandardCharsets.UTF_8, withCustomImport(body.getBytes(StandardCharsets.UTF_8)));
        assertTrue(g.getResult("en").getContent().toString().contains("REMOTE"));
    }

    @Test
    void remoteImportWithBadSha256Throws(@TempDir Path tmp) throws IOException {
        File src = writeFixture(tmp,
                "<!--@nrg.allowRemoteImports=true-->\n${widget:import(url='https://example.com/x', sha256='0000000000000000000000000000000000000000000000000000000000000000')}\n");
        Generator g = new Generator(src, StandardCharsets.UTF_8, withCustomImport("REMOTE".getBytes(StandardCharsets.UTF_8)));
        assertThrows(RuntimeException.class, () -> g.getResult("en"));
    }

    @Test
    void remoteImportRequireSha256AndNoHashThrows(@TempDir Path tmp) throws IOException {
        String prop = NRGConstants.PROPERTY_REQUIRE_SHA256_FOR_REMOTE;
        String old = System.getProperty(prop);
        System.setProperty(prop, "true");
        try {
            File src = writeFixture(tmp, "<!--@nrg.allowRemoteImports=true-->\n${widget:import(url='https://example.com/x')}\n");
            Generator g = new Generator(src, StandardCharsets.UTF_8, withCustomImport("X".getBytes(StandardCharsets.UTF_8)));
            assertThrows(RuntimeException.class, () -> g.getResult("en"));
        } finally {
            if (old == null) System.clearProperty(prop); else System.setProperty(prop, old);
        }
    }

    @Test
    void remoteImportPathAndUrlConflictThrows(@TempDir Path tmp) throws IOException {
        File src = writeFixture(tmp, "<!--@nrg.allowRemoteImports=true-->\n${widget:import(path='x.txt', url='https://example.com/x')}\n");
        Generator g = new Generator(src, StandardCharsets.UTF_8, withCustomImport("X".getBytes(StandardCharsets.UTF_8)));
        assertThrows(RuntimeException.class, () -> g.getResult("en"));
    }

    @Test
    void remoteSrcMdRunsGenerator(@TempDir Path tmp) throws IOException {
        String body = "<!--@unprocessedParameter=foo-->\nresult: ${unprocessedParameter}";
        File src = writeFixture(tmp, "<!--@nrg.allowRemoteImports=true-->\n${widget:import(url='https://example.com/x.src.md')}\n");
        Generator g = new Generator(src, StandardCharsets.UTF_8, withCustomImport(body.getBytes(StandardCharsets.UTF_8)));
        String out = g.getResult("en").getContent().toString();
        assertTrue(out.contains("result: foo"), () -> "unexpected: " + out);
    }

    @Test
    void remoteNonSrcMdDoesNotRunGenerator(@TempDir Path tmp) throws IOException {
        // For a .txt URL, run-generator defaults to false — variable substitution should NOT happen.
        String body = "result: ${someVar}";
        File src = writeFixture(tmp,
                "<!--@nrg.allowRemoteImports=true-->\n<!--@someVar=foo-->\n${widget:import(url='https://example.com/x.txt')}\n");
        Generator g = new Generator(src, StandardCharsets.UTF_8, withCustomImport(body.getBytes(StandardCharsets.UTF_8)));
        String out = g.getResult("en").getContent().toString();
        assertTrue(out.contains("result: ${someVar}"), () -> "unexpected (substitution should NOT have happened): " + out);
    }

    private static File writeFixture(Path tmp, String body) throws IOException {
        File f = tmp.resolve("test.src.md").toFile();
        org.apache.commons.io.FileUtils.writeStringToFile(f, body, StandardCharsets.UTF_8);
        return f;
    }

    private static UrlOpener stubOpener(byte[] body) {
        return (url, timeout, redirects) -> new UrlOpener.Response(body);
    }

    private static List<NRGWidget> withCustomImport(byte[] remoteBody) {
        return Arrays.asList(new ImportWidget(new RemoteFetcher(stubOpener(remoteBody), Clock.systemUTC())));
    }

    @Test
    public void importHeadingOffsetShiftsHeadings() throws IOException {
        String body = render("ImportWidgetTest/heading-offset/README-basic.src.md");
        // Imported H1 -> H2; imported H2 -> H3
        assertTrue(body.contains("## Quick start"), body);
        assertTrue(body.contains("### Installation"), body);
        // Parent's own headings are unaffected
        assertTrue(body.contains("# Project"), body);
        assertTrue(body.contains("## Section A"), body);
        assertTrue(body.contains("## Section B"), body);
    }

    @Test
    public void invalidHeadingOffsetThrows() {
        RuntimeException ex = assertThrows(RuntimeException.class,
                () -> render("ImportWidgetTest/heading-offset/README-invalid.src.md"));
        String msg = ex.getMessage() + " || cause: " + (ex.getCause() == null ? "<none>" : ex.getCause().getMessage());
        assertTrue(msg.contains("heading-offset must be an integer"),
                () -> "unexpected: " + msg);
    }

    @Test
    public void headingOffsetWithWrapTrueThrows() {
        RuntimeException ex = assertThrows(RuntimeException.class,
                () -> render("ImportWidgetTest/heading-offset/README-wrap-conflict.src.md"));
        String msg = ex.getMessage() + " || cause: " + (ex.getCause() == null ? "<none>" : ex.getCause().getMessage());
        assertTrue(msg.contains("cannot be combined with wrap"),
                () -> "unexpected: " + msg);
    }

    @Test
    public void headingOffsetZeroIsNoOp() throws IOException {
        String body = render("ImportWidgetTest/heading-offset/README-zero.src.md");
        assertTrue(body.contains("# Quick start"), body);
        assertTrue(body.contains("## Installation"), body);
    }

    @Test
    public void headingOffsetAppliesAfterSubGeneratorIncludingNestedImports() throws IOException {
        String body = render("ImportWidgetTest/heading-offset/README-nested.src.md");
        assertTrue(body.contains("## Outer heading"), body);
        assertTrue(body.contains("## Inner heading"), body);
        // Original H1 levels should NOT remain. Note: `body.contains("# Outer heading")` would
        // match `## Outer heading` as a substring, so check line-by-line instead.
        for (String line : body.split("\\R", -1)) {
            assertNotEquals("# Outer heading", line, body);
            assertNotEquals("# Inner heading", line, body);
        }
    }

    @Test
    public void tocReflectsShiftedHeadingLevels() throws IOException {
        String body = render("ImportWidgetTest/heading-offset/README-toc.src.md");
        // The shifted "## Quick start" appears as a top-level entry in the TOC,
        // and "### Installation" appears nested under it.
        assertTrue(body.contains("[Quick start](#quick-start)"), body);
        assertTrue(body.contains("[Installation](#installation)"), body);
        int qsIdx = body.indexOf("[Quick start]");
        int instIdx = body.indexOf("[Installation]");
        assertTrue(qsIdx > 0 && instIdx > qsIdx, "TOC ordering looks off: " + body);
    }

    @Test
    public void headingOffsetSkipsFencedCodeBlocksInImportedContent() throws IOException {
        String body = render("ImportWidgetTest/heading-offset/README-fence.src.md");
        assertTrue(body.contains("## Quick start"), body);
        assertTrue(body.contains("### Next steps"), body);
        // The bash comment must remain a single '#' (not shifted).
        assertTrue(body.contains("# this is a shell comment, not a heading"), body);
        assertFalse(body.contains("## this is a shell comment, not a heading"), body);
    }
}