package com.nanolaba.nrg.core;

import com.nanolaba.nrg.NRG;

import java.io.File;
import java.util.Collection;
import java.util.HashMap;
import java.util.Map;

public class Generator {


    private final GeneratorConfig config;
    private final Map<String, GenerationResult> results = new HashMap<>();

    public Generator(File sourceFile, String source) {
        config = new GeneratorConfig(sourceFile, source);
        generateContents();
    }

    private void generateContents() {
        for (String language : config.getLanguages()) {
            results.put(language, generateContent(language));
        }
    }

    private GenerationResult generateContent(String language) {
        GenerationResult result = new GenerationResult(language);
        result.getContent().append(generateHeadComment(language));

        config.getSourceLinesStream()
                .filter(t -> t.isLineVisible(language))
                .map(t -> t.generateLine(language))
                .forEachOrdered(line -> result.getContent().append(line).append(System.lineSeparator()));

        return result;
    }

    protected String generateHeadComment(String language) {
        return "<!-- This file was automatically generated by Nanolaba Readme Generator (NRG) " + NRG.getVersion() + " -->" + System.lineSeparator() +
               "<!-- Visit https://github.com/nanolaba/readme-generator for details -->" + System.lineSeparator();
    }

    public GenerationResult getResult(String language) {
        return results.get(language);
    }

    public Collection<GenerationResult> getResults() {
        return results.values();
    }

    public GeneratorConfig getConfig() {
        return config;
    }
}
